/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f2e9c5c9fef9b23969889883c4ec9d40)
interface __BaseEnv_Env {
	UI_CACHE: KVNamespace;
	ASSETS: R2Bucket;
	FEEDBACK: AnalyticsEngineDataset;
	AI: Ai;
	AI_GATEWAY_ID: "personal-website-test" | "personal-website";
	PROMPTFOO_API_KEY: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface TestEnv {
		UI_CACHE: KVNamespace;
		ASSETS: R2Bucket;
		FEEDBACK: AnalyticsEngineDataset;
		AI: Ai;
		AI_GATEWAY_ID: "personal-website-test";
		PROMPTFOO_API_KEY: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "PROMPTFOO_API_KEY" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID">> {}
}
