export interface Env {
  // AI binding for gateway access (generated by wrangler types)
  AI: Ai;
  // Gateway ID as env var for flexibility
  AI_GATEWAY_ID: string;

  // Storage bindings
  UI_CACHE: KVNamespace;
  ASSETS: R2Bucket;

  // Analytics Engine for feedback tracking
  FEEDBACK: AnalyticsEngineDataset;
}

export interface GenerateRequest {
  visitorTag: string;
  customIntent?: string;
  portfolioContent: PortfolioContent;
}

export interface PortfolioContent {
  personal: {
    name: string;
    title: string;
    bio: string;
    contact: {
      email: string;
      linkedin: string;
      github: string;
    };
    location?: string;
    resumeUrl?: string;
  };
  projects: Array<{
    id: string;
    title: string;
    description: string;
    technologies: string[];
    image: string;
    links: {
      demo?: string;
      github?: string;
    };
    tags: string[];
    featured?: boolean;
  }>;
  experience: Array<{
    id: string;
    company: string;
    role: string;
    period: string;
    description: string;
    highlights?: string[];
  }>;
  skills: string[];
  education: Array<{
    id: string;
    institution: string;
    degree: string;
    period: string;
    highlights?: string[];
  }>;
  hobbies?: string[];
  photos?: Array<{
    path: string;
    description: string;
  }>;
}

export interface GeneratedLayout {
  layout: 'single-column' | 'two-column' | 'hero-focused';
  theme: { accent: string };
  sections: Array<{
    type: string;
    props: Record<string, unknown>;
  }>;
}

export interface AIGatewayResponse {
  choices?: Array<{
    message: {
      content: string;
    };
  }>;
  error?: {
    message: string;
  };
}

export interface CategorizationResult {
  status: 'matched' | 'new_tag' | 'rejected';
  tagName: string;
  displayName: string;
  guidelines: string;
  confidence: number;
  reason?: string;
}

export interface StoredTag {
  tagName: string;
  displayName: string;
  guidelines: string;
  createdAt: string;
  mappedFrom?: string;
  isCustom: boolean;
}

// Feedback types for like/dislike functionality
export interface FeedbackRequest {
  feedbackType: 'like' | 'dislike';
  audienceType: string;
  cacheKey: string;
  sessionId: string;
}

export interface FeedbackResponse {
  success: boolean;
  message: string;
  regenerate?: boolean;
  rateLimited?: boolean;
  retryAfter?: number;
}

export interface RateLimitEntry {
  lastDislike: number;
  count: number;
}

// Visitor context extracted from Cloudflare request
export interface VisitorContext {
  geo: {
    country?: string; // ISO 3166-1 Alpha 2 (e.g., "US", "GB")
    city?: string; // e.g., "Austin"
    continent?: string; // e.g., "NA", "EU"
    timezone?: string; // e.g., "America/Chicago"
    region?: string; // e.g., "Texas"
    isEUCountry: boolean;
  };
  device: {
    type: 'mobile' | 'tablet' | 'desktop';
    browser?: string; // e.g., "Chrome", "Safari"
    os?: string; // e.g., "iOS", "macOS"
  };
  time: {
    localHour: number; // 0-23
    timeOfDay: 'morning' | 'afternoon' | 'evening' | 'night';
    isWeekend: boolean;
  };
  network: {
    httpProtocol: string; // e.g., "HTTP/2"
    colo: string; // Cloudflare datacenter code
  };
}

// UI hints derived from visitor context
export interface UIHints {
  suggestedTheme: 'light' | 'dark' | 'system';
  preferCompactLayout: boolean;
}

// GitHub Activity API types
export interface GitHubEvent {
  type: string;
  created_at: string;
  payload?: {
    commits?: Array<{ sha: string }>;
    size?: number;
  };
}

export interface GitHubActivityResponse {
  contributions: Array<{
    date: string;
    count: number;
  }>;
  totalCommits: number;
  recentActivity: number; // commits in last 30 days
}
